using Grpc.Core;
using Reglamentator.WebAPI;

namespace Reglamentator.WebAPI.Services;

public class UserService : User.UserBase
{
    private readonly ILogger<UserService> _logger;

    public UserService(ILogger<UserService> logger)
    {
        _logger = logger;
    }

    public override Task<CreateUserResponse> CreateUser(CreateUserRequest request, ServerCallContext context)
    {
        _logger.LogInformation("Creating user with Telegram ID: {TelegramId}", request.TelegramId);
        
        return Task.FromResult(new CreateUserResponse
        {
            User = new TelegramUserDto
            {
                Id = 1, // This should be generated by your data layer
                TelegramId = request.TelegramId
            },
            Status = new StatusResponse
            {
                StatusMessage = "User created successfully",
                IsSuccess = true
            }
        });
    }
}
