version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    container_name: reglamentator-bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM__Token}
      - DOTNET_ENVIRONMENT=Production
